swagger: '2.0'
info:
  description: 'This is a sample server Covid server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.'
  version: 1.0.0
  title: Swagger Covid
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache-2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: hospital
    description: Everything about your Hospital
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
host: localhost:8080
basePath: /v2      
schemes:
  - http
paths:
  /hospital:
    post:
      tags:
        - hospital
      summary: Add a new hospital to the store
      description: ''
      operationId: addHospital
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Hospital object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Hospital'
      responses:
        '405':
          description: Invalid input
    put:
      tags:
        - hospital
      summary: Update an existing hospital
      description: ''
      operationId: updateHospital
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Hospital object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Hospital'
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: Hospital not found
        '405':
          description: Validation exception
    get:
      tags:
        - hospital
      summary: Get all Hospitals
      description: ''
      operationId: getAllHospitals
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Hospital'
  /hospital/findByAvailability:
    get:
      tags:
        - hospital
      summary: Finds Hospitals by Availability
      description: Fet Hospital details according to their availability
      operationId: findHospitalsByAvailability
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Hospital'
  '/hospital/{hospitalId}':
    get:
      tags:
        - hospital
      summary: Find hospital by ID
      description: Returns a single hospital
      operationId: getHospitalById
      produces:
        - application/json
      parameters:
        - name: hospitalId
          in: path
          description: ID of hospital to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Hospital'
        '400':
          description: Invalid ID supplied
        '404':
          description: Hospital not found
    delete:
      tags:
        - hospital
      summary: Deletes a hospital
      description: ''
      operationId: deleteHsopital
      produces:
        - application/json
      parameters:
        - name: hospitalId
          in: path
          description: Hospital id to delete
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid hospital value
definitions:
  Hospital:
    title: Hospital
    description: Hospital Details and Store
    type: object
    properties:
      id:
        type: string
      hospitalName:
        type: string
      city:
        type: string
      state:
        type: string
      country:
        type: string
      noOfBeds:
        type: integer
        format: int64
  Patient:
    title: Patient
    description: Details about the patient
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      address:
        type: string
      age:
        type: string
      state:
        type: string
      hospitalId: 
        $ref: '#/definitions/Hospital'
  Doctor:
    title: Doctor
    description: A doctor who is serving the patient
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      phone:
        type: string
      covidStatus:
        type: string
        description: covid status
        enum:
          - clean
          - suffering
          - recovered
  State:
    title: State
    description: Details of State
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
  